name: Pull actions

on:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: Validate
    steps:
        - uses: "actions/checkout@v2"

        - name: HACS validation
          uses: "hacs/integration/action@main"
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CATEGORY: "integration"

        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  style:
    runs-on: ubuntu-latest
    name: Check style formatting
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Set up Python 3.8
      with:
        python-version: 3.8
    - uses: pre-commit/action@v2
